### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by Wolfr** [NullVoxPopuli/ember-lifecycle-component#5]
![image](https://user-images.githubusercontent.com/12690/84686751-d2566f80-af3c-11ea-99ec-b9d60025aafe.png)

> A component with additional lifecycles for times when you may need need a template

I assume this has to be "you may not need a template" :)

**Comment by NullVoxPopuli** [comment]
Yes! I should probably deprecate this repo though, cause use/resource is the path forward

**Comment by NullVoxPopuli** [comment]
updated!
